config/routes.rb
Rails.application.routes.draw do

  root   'static_pages#home'
  get    '/signup', to: 'users#new'
  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get    '/edit-basic-info/:id', to: 'users#edit_basic_info', as: :basic_info
  patch  'update-basic-info',    to: 'users#update_basic_info'
  get    'users/:id/attendances/:date/edit',   to: 'attendances#edit',   as: :edit_attendances
  patch  'users/:id/attendances/:date/update', to: 'attendances#update', as: :update_attendances
  resources :users do
  resources :attendances, only: :create
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :attendances, dependent: :destroy  
  #dependent: :destroyというオプションを指定すると、ユーザーが削除された時に、そのユーザーの持つAttendanceモデルのデータも一緒に削除されるようになります。
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true 
  # allow_nil: true 「パスワード（と確認用パスワード）を入力している場合は更新」、「パスワードを入力していない場合は検証をスルーして更新（他の属性の検証は勿論実行される）」
  validates :department, length: { in: 3..50 }, allow_blank: true #空の検証をスキップさせるときに使用する
  
  def self.search(search)  #ここでのself.はUser.を意味する
    if search
      where(['name LIKE ?', "%#{search}%"])  #検索とnameの部分一致を表示。User.は省略
    else 
      all  #全て表示。User.は省略
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  #ログインしていないユーザーが保護されたページにアクセスした場合、ログインページへ転送し、かつメッセージを添える。
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: [:destroy, :edit_basic_info, :update_basic_info]
  before_action :correct_referer
  
  def index
    @users = User.paginate(page: params[:page]).search(params[:search])
    #@users = User.all
    
  end
  
  def show
    @user = User.find(params[:id])
    @first_day = first_day(params[:first_day])
    @last_day  = @first_day.end_of_month
    (@first_day..@last_day).each do |day|
      
      unless @user.attendances.any? {|attendance| attendance.worked_on == day}
        record = @user.attendances.build(worked_on: day) #buildメソッド:あるモデルに関連づいたモデルのデータを生成する
        record.save
#@userに紐付いた当月の初日から末日までのattendancesテーブルのレコードがあるか確認,ない場合は該当する日付をworked_onに代入し、保存する」という処理が実行される。
#このany?メソッドは、ブロック変数attendanceに要素を入れながらブロック（ここではattendance.worked_on == day）を実行し、ブロックが真（true）を返した時は、
#ブロック実行をその時点で中断しtrueを返します。ブロックの戻り値が全て偽（false）である時はfalseが返されます。      
      end
    end
    @dates = user_attendances_month_date
    @worked_sum = @dates.where.not(started_at: nil).count #where.not:nil以外を取得, count:条件に合った要素の数だけを取得
  end  
    
  def new
    @user = User.new #新規作成されたUserオブジェクトをインスタンス変数に代入する
  end
  
  def create
    @user = User.new(user_params)
    if @user.save 
       log_in @user  # 保存成功後、ログインします。
       flash[:success] = "ユーザの新規作成に成功しました。"
       redirect_to @user
    else
      render 'new'
    end  
  end
 
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      # 更新に成功した場合の処理
      flash[:success] = "ユーザー情報を更新しました。"
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:succerss] = "削除しました。"
    redirect_to users_url
  end 
  
  def edit_basic_info 
    @user = User.find(params[:id])
  end
  
  def update_basic_info
    @user = User.find(params[:id])
    if @user.update_attributes(basic_info_params)
      flash[:success] = "基本情報を更新しました。"
      redirect_to @user
    else
      render 'edit_basic_info'
    end
  end 

  #def basic_info  #特定のユーザーの指定基本時間を表示する
   # @user = User.find_by(id: params[:id])
  #end

 private
 
  def user_params   #Strong Parameters
    params.require(:user).permit(:name, :email, :department, :password, :password_confirmation)
  end
end

  def basic_info_params  
    params.require(:user).permit(:basic_time, :work_time)
  end

# beforeアクション

# ログイン済みユーザーか確認
# ログインしていないユーザーが保護されたページにアクセスした場合、ログインページへ転送し、かつメッセージを添える。
  def logged_in_user
    unless logged_in?   # if !logged_in?と同じ
      store_location
      flash[:danger] = "ログインしてください。"
      redirect_to login_url
    end
  end

# 正しいユーザーかどうか確認,ユーザーが自身の情報のみを編集・更新できるようになる
  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end 

# 管理者かどうか確認
  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end

  def correct_referer  #一般ユーザーが他のユーザーのIDをURLに直接入力禁止　before_action定義
  if request.referer.nil?
    redirect_to root_url
  end
end

app/helpers/users_helper.rb
module UsersHelper
  
# 基本時間などの値を、指定の書式にフォーマットして返す
def format_basic_time(datetime)
  format("%.2f", ((datetime.hour * 60) + datetime.min)/60.0)
end
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', object: @user %>
  
  <%= f.label :名前 %>
  <%= f.text_field :name, class: 'form-control' %>
  
  <%= f.label :メールアドレス %>
  <%= f.email_field :email, class: 'form-control' %>
  
  <%= f.label :所属 %>
  <%= f.text_field :department, class: 'form-control' %>
  
  <%= f.label :パスワード %>
  <%= f.password_field :password, class: 'form-control' %>
  
  <%= f.label :パスワード確認 %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>  

app/views/users/_user.html.erb
<li>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "基本情報編集", basic_info_path(user) %> 
    | <%= link_to "削除", user, method: :delete, data: { confirm: "削除してよろしいですか？" } %>
  <% end %>                       
</li>

<% if false %> view/erbコメントアウト<% end %>

app/views/users/edit.html.erb
<% provide(:title, 'アカウント編集') %>
<% provide(:button_text, '更新') %>
<h1>アカウント情報の更新</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
    
  </div>
</div>

app/views/users/edit_basic_info.html.erb
<% provide(:title, "基本情報編集") %>

<h1>基本情報の更新</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: update_basic_info_path(params: {id: @user.id})) do |f| %>
      <%= render 'shared/error_messages', object: @user %>
      
      <%= f.label :基本勤務時間 %>
      <%= f.time_field :basic_time, class: 'form-control' %>
      
      <%= f.label :指定勤務時間 %>
      <%= f.time_field :work_time, class: 'form-control' %>
      
      <%= f.submit "更新", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, '一覧') %>

<% if params[:search].present? %>
  <h1>検索結果</h1>
<% else %>
  <h1>ユーザ一覧</h1>
<% end %>

<!--  検索拡張機能  -->
<form class="form-inline text-right">
<p>ユーザー名検索</p>

<div class="form-group">
    <%= form_tag(users_path, :method => 'get' ) do %>
    <%= text_field_tag :search, params[:search], placeholder: "キーワードを入力" %>
</div>
<div class="form-group">
    <%= submit_tag '検索', :name => nil %>
    <% end %>
  </div>    
</form>


<%= will_paginate @users, :previous_label => '&lt 前へ', :next_label => '次へ &gt' %>

<ul class="users">
    <%= render @users %>
</ul>

<%= will_paginate @users, :previous_label => '&lt 前へ', :next_label => '次へ &gt' %>

app/views/users/new.html.erb
<% provide(:title, 'ユーザ作成') %>
<% provide(:button_text, '作成') %>
<h1>アカウント作成</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
    
  </div>  
</div>

app/views/users/show.html.erb
<% provide(:title, '勤怠表示') %>
<div>
  <table class = "table-bordered table-condensed">
    <tr>
      <td>
        <%= link_to "←", user_path(params: {id: @user.id, first_day: @first_day.prev_month}),
        class: "btn btn-xs btn-primary" %>
        &emsp;<%= @first_day.to_s(:year_month) %> 時間管理表&emsp;
        <%= link_to "→", user_path(params: {id: @user.id, first_day: @first_day.next_month}),
        class: "btn btn-xs btn-primary" %>
      </td>
      <td>指定勤務時間　<%= format_basic_time(@user.work_time) %></td>
      <td>基本勤務時間　<%= format_basic_time(@user.basic_time) %></td>
      <td>初日 <%= @first_day.to_s(:date) %></td>
    </tr>

    <tr>
      <td>所属：<%= @user.department.present? ? @user.department : "未設定" %></td>
      <td>氏名：<%= @user.name %></td>
      <td>出勤日数 <%= @worked_sum %>日</td>
      <td>締日 <%= @last_day.to_s(:date) %></td>
    </tr>
  </table>
  
  <%= link_to "勤怠を編集", edit_attendances_path(@user, @first_day), class: "btn btn-primary" %>
  
  <table class = "table-bordered table-striped table-condensed"
    <thead>
    <tr><!--rowspan:縦結合、colspan：横結合-->
      <th rowspan = "2">日付</th>
      <th rowspan = "2">曜日</th>
      <th colspan = "3">出社</th>
      <th colspan = "3">退社</th>
      <th rowspan = "2">在社時間</th>
      <th rowspan = "2">備考</th>
    </tr>
    
    <tr>
      <th>時</th>
      <th>分</th>
      <th></th>
      <th>時</th>
      <th>分</th>
      <th></th>
    </tr>
   </thead>
   
   <tbody>
     <% @dates.each do |day| %>
      <% 
         css_class = 
         case%w{日 月 火 水 木 金 土}[day.worked_on.wday]
         when '土'
         'text-primary'
         when '日'
         'text-danger'
         end
      %>
      <tr>
        <td><%= day.worked_on.to_s(:date) %></td>
        <td class="<%= css_class %>"><%= %w{日 月 火 水 木 金 土}[day.worked_on.wday] %></td>
        <td><%= day.started_at.to_s(:hour) if day.started_at.present? %></td>
        <td><%= day.started_at.floor_to(15.minutes).to_s(:min)  if day.started_at.present? %></td>
        <td>
          <% if day.worked_on == Date.today && day.started_at.nil? %>
            <%= button_to "出社", user_attendances_path(@user), class: "btn btn-xs btn-primary" %>
          <% end %>  
        </td>
        <td><%= day.finished_at.to_s(:hour) if day.finished_at.present? %></td>
        <td><%= day.finished_at.floor_to(15.minutes).to_s(:min)  if day.finished_at.present? %></td>
        <td>
          <% if day.worked_on == Date.today && day.started_at.present? && day.finished_at.nil? %>
            <%= button_to "退社", user_attendances_path(@user), class: "btn btn-xs btn-primary" %>
          <% end %>  
        </td>
        <td>
          <% if day.started_at.present? && day.finished_at.present? %>
            <%= working_times(day.started_at.floor_to(15.minutes), day.finished_at.floor_to(15.minutes)) %>
            <% seconds = (day.finished_at.floor_to(15.minutes) - day.started_at.floor_to(15.minutes)) %>
            <% @total_seconds = @total_seconds.to_i + seconds %>
          <% end %>  
        </td>
        <td><%= day.note %></td>
      </tr>
    <% end %>  
   </tbody>
   
   <tfoot>
     <tr>
       <td colspan = "2"></td>
       <td colspan = "6">総合勤務時間:<%= format_basic_time(@user.basic_time).to_f * @worked_sum %></td>
       <td>累計在社時間:<%= working_times_sum(@total_seconds) unless @total_seconds.nil? %></td>
       <td></td>
     </tr>
   </tfoot>
  </table>  
</div>