config/routes.rb
Rails.application.routes.draw do

  root   'static_pages#home'
  get    '/signup', to: 'users#new'
  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get    '/edit-basic-info/:id', to: 'users#edit_basic_info', as: :basic_info
  patch  'update-basic-info',    to: 'users#update_basic_info'
  get    'users/:id/attendances/:date/edit',   to: 'attendances#edit',   as: :edit_attendances
  patch  'users/:id/attendances/:date/update', to: 'attendances#update', as: :update_attendances
  resources :users do
  resources :attendances, only: :create
  end
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user
 
  validates :worked_on, presence: true
  
  # 出勤時間が存在しない場合、退勤時間は無効 　追加機能No.7
  validate :finished_at_is_invalid_without_a_started_at
  # 出勤・退勤時間どちらも存在する時、出勤時間より早い退勤時間は無効  追加機能No.8
  validate :started_at_than_finished_at_fast_if_invalid
  
  def finished_at_is_invalid_without_a_started_at
    errors.add(:started_at, "を入力してください") if started_at.blank? && finished_at.present?
  end
  
  def started_at_than_finished_at_fast_if_invalid
    if started_at.present? && finished_at.present?
      errors.add(:started_at,"より退勤時間の方が早くなっています") if started_at > finished_at
    end 
  end  
end

app/helpers/attendances_helper.rb
module AttendancesHelper
  
  def current_time
    Time.new(
      Time.now.year,
      Time.now.month,
      Time.now.day,
      Time.now.hour,
      Time.now.min, 0
    )
  end

  def working_times(started_at, finished_at)
    format("%.2f", (((finished_at - started_at) / 60) / 60.0))
  end

  def working_times_sum(seconds)
    format("%.2f", seconds / 60 / 60.0)
  end

  def first_day(date)
    !date.nil? ? Date.parse(date) : Date.current.beginning_of_month
  end
  
  def user_attendances_month_date
    @user.attendances.where('worked_on >= ? and worked_on <= ?', @first_day, @last_day).order('worked_on')
  end  

# 不正な値があるか確認する
def attendances_invalid?
    attendances = true
    attendances_params.each do |id, item|
      if item[:started_at].blank? && item[:finished_at].blank?
        next
      elsif item[:started_at].blank? || item[:finished_at].blank?
        attendances = false
        break
      elsif item[:started_at] > item[:finished_at]
        attendances = false
        break
      end
    end
    return attendances  
end
end

app/views/attendances/edit.html.erb
<% provide(:title,"勤怠編集" ) %>
<div>
  <h1>勤怠編集画面</h1>
  <%= form_for(@user, url: update_attendances_path, method: :patch) do |f| %>
  <table class = "table-bordered table-striped table-condensed">
    <thead>
      <tr>
        <th>日付</th>
        <th>曜日</th>
        <th>出社</th>
        <th>退社</th>
        <th>在社時間</th>
        <th>備考</th>
      </tr>
    </thead>
    <tbody>
      <% @dates.each do |day| %>
       <% css_class = case%w{日 月 火 水 木 金 土}[day.worked_on.wday]
         when '土'
         'text-primary'
         when '日'
         'text-danger'
         end %>
      <%= fields_for "attendances[]", day do |af| %>
      <tr>
        <td><%= day.worked_on.to_s(:date) %></td>
        <td class = "<%= css_class %>"><%= %w{日 月 火 水 木 金 土}[day.worked_on.wday] %></td>
        
      <% if (Date.current < day.worked_on) %>
        <td><%= af.time_field :started_at, readonly: true, class: "form-control" %></td>
        <td><%= af.time_field :finished_at, readonly: true, class: "form-control" %></td>
      <% else %>
        <td><%= af.time_field :started_at, class: "form-control" %></td>
        <td><%= af.time_field :finished_at, class: "form-control" %></td>
      <% end %>

        <td>
          <% if day.started_at.present? && day.finished_at.present? %>
            <%= working_times(day.started_at, day.finished_at) %>
          <% end %>
        </td>
        <td><%= af.text_field :note, class: "form-control" %></td>
      </tr>
      <% end %>
     <% end %>  
    </tbody>
  </table>
  <div class= "btn-attendances-update">
    <%= link_to "キャンセル", user_path(@user, params:{first_day: @first_day }), class: "btn btn-default btn-block btn-primary" %>
    <%= f.submit "編集を保存する", class: "btn btn-primary" %>
  </div>
  <% end %>
</div>